# Generated by Django 5.2 on 2025-07-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
    ]
