# Generated by Django 5.2 on 2025-08-07 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_collectibleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='athletes',
            field=models.ManyToManyField(related_name='collectibles', to=settings.AUTH_USER_MODEL),
        ),
    ]
