# Generated by Django 5.2 on 2025-08-08 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_collectibleitem_athletes'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(null=True),
        ),
    ]
