# Generated by Django 5.2 on 2025-08-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_alter_position_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(null=True),
        ),
    ]
