# Generated by Django 5.2 on 2025-08-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0015_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
